/**
 * agent.ts — typed client for the local Go agent at localhost:7071.
 *
 * HTTP calls (GET/POST/DELETE) go through the Tauri Rust commands
 * (agent_get / agent_post / agent_delete → reqwest) because direct
 * fetch from the WebView to http:// is blocked by Tauri's security model.
 *
 * SSE uses EventSource which works natively from the WebView.
 */

import { invoke } from '@tauri-apps/api/core'

const SSE_BASE = 'http://127.0.0.1:7071'

// SSE resilience tuning. Exposed as constants so they're easy to tweak.
const SSE_INITIAL_BACKOFF_MS = 1_000
const SSE_MAX_BACKOFF_MS = 30_000
/** If no event (including heartbeat) arrives within this window, force reconnect. */
const SSE_WATCHDOG_MS = 30_000

// Ephemeral token generated by Tauri on each agent launch.
// Fetched once at app boot and reused for the session.
let _agentToken = ''

/**
 * Initialize the agent token from Tauri. Must be called once before using
 * agent.subscribe(). Called automatically by App.vue on setup.
 */
export async function initAgentToken(): Promise<void> {
  try {
    _agentToken = await invoke<string>('get_agent_token')
  } catch {
    // Dev mode without Tauri shell: token stays empty → agent allows all.
    _agentToken = ''
  }
}

// ── Types ────────────────────────────────────────────────────────────────────

export interface VPNStatus {
  connected: boolean
  server_name: string
  server_id: string
  assigned_ip: string
  server_public_ip: string
  mesh_ip: string
  bytes_sent: number
  bytes_recv: number
}

export interface MeshStatus {
  active: boolean
  mesh_id: string
  mesh_ip: string
  public_ip: string
  is_exit_node: boolean
  full_tunnel: boolean
  exit_node_host?: string
  exit_node_port?: number
  exit_node_scheme?: string
  peers: MeshPeer[]
}

export interface ProtectionStatus {
  kill_switch_active: boolean
  dns_protected: boolean
  mode?: string
  last_error?: string
}

export interface MeshPeer {
  mesh_ip: string
  display_name: string
  public_ip?: string
  proxy_port?: number
  is_exit_node?: boolean
}

export interface AuthStatus {
  logged_in: boolean
  username: string
  expires_at: number | null
}

export interface AgentSnapshot {
  vpn: VPNStatus
  mesh: MeshStatus
  auth: AuthStatus
  protection: ProtectionStatus
  kill_switch?: { active: boolean }
  dns_protected?: boolean
}

export interface Server {
  id: string
  name: string
  host: string
  endpoint: string
  location: string
  country_code: string
  wg_port: number
  public_key: string
  is_active: boolean
  proxy_port: number
  supports_wireguard: boolean
  supports_proxy: boolean
  supports_mesh_exit: boolean
}

export interface ExitNode {
  user_id: string
  mesh_ip: string
  proxy_scheme: string
  proxy_port: number
  supports_tcp: boolean
  supports_udp: boolean
  is_active: boolean
}

export type AgentEvent =
  | { type: 'vpn_status'; data: VPNStatus }
  | { type: 'mesh_status'; data: MeshStatus }
  | { type: 'auth_status'; data: AuthStatus }
  | { type: 'protection_status'; data: ProtectionStatus }
  | { type: 'error'; data: { message: string } }

// ── Tauri IPC helpers ─────────────────────────────────────────────────────────

async function get<T>(path: string): Promise<T> {
  return invoke<T>('agent_get', { path })
}

async function post<T>(path: string, body?: unknown): Promise<T> {
  return invoke<T>('agent_post', { path, body: body !== undefined ? JSON.stringify(body) : '{}' })
}

async function del<T>(path: string): Promise<T> {
  return invoke<T>('agent_delete', { path })
}

// ── API ──────────────────────────────────────────────────────────────────────

export const agent = {
  /** Get current snapshot of all state */
  status: () => get<AgentSnapshot>('status'),

  /** Subscribe to SSE events; returns cleanup fn */
  subscribe(cb: (e: AgentEvent) => void): () => void {
    let es: EventSource | null = null
    let stopped = false
    let reconnectTimer: ReturnType<typeof setTimeout> | null = null
    let watchdogTimer: ReturnType<typeof setTimeout> | null = null
    let backoffMs = SSE_INITIAL_BACKOFF_MS

    const clearTimers = () => {
      if (reconnectTimer) { clearTimeout(reconnectTimer); reconnectTimer = null }
      if (watchdogTimer) { clearTimeout(watchdogTimer); watchdogTimer = null }
    }

    const resetWatchdog = () => {
      if (watchdogTimer) clearTimeout(watchdogTimer)
      watchdogTimer = setTimeout(() => {
        if (!stopped) connect()
      }, SSE_WATCHDOG_MS)
    }

    const connect = () => {
      if (stopped) return
      clearTimers()
      if (es) { try { es.close() } catch { /* ignore */ } }

      const url = _agentToken
        ? `${SSE_BASE}/events?token=${encodeURIComponent(_agentToken)}`
        : `${SSE_BASE}/events`
      es = new EventSource(url)

      const parse = (raw: string, type: string) => {
        resetWatchdog()
        backoffMs = SSE_INITIAL_BACKOFF_MS // reset backoff on successful message
        try {
          const snap = JSON.parse(raw) as AgentSnapshot
          if (type === 'vpn_status') cb({ type: 'vpn_status', data: snap.vpn })
          else if (type === 'mesh_status') cb({ type: 'mesh_status', data: snap.mesh })
          else if (type === 'auth_status') cb({ type: 'auth_status', data: snap.auth })
          else if (type === 'protection_status') cb({ type: 'protection_status', data: snap.protection })
          else if (type === 'snapshot') {
            cb({ type: 'vpn_status', data: snap.vpn })
            cb({ type: 'mesh_status', data: snap.mesh })
            cb({ type: 'auth_status', data: snap.auth })
            cb({ type: 'protection_status', data: snap.protection })
          }
        } catch (e) {
          // Malformed payload from agent — surface in dev for diagnosis.
          // `import.meta.env` is provided by Vite at build-time.
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          if ((import.meta as any).env?.DEV) {
            console.warn('[agent] SSE parse error', { type, error: e, raw })
          }
        }
      }

      const onVpn = (e: MessageEvent) => parse(e.data, 'vpn_status')
      const onMesh = (e: MessageEvent) => parse(e.data, 'mesh_status')
      const onAuth = (e: MessageEvent) => parse(e.data, 'auth_status')
      const onProtection = (e: MessageEvent) => parse(e.data, 'protection_status')
      const onSnap = (e: MessageEvent) => parse(e.data, 'snapshot')
      const onHeartbeat = () => resetWatchdog()

      es.addEventListener('vpn_status', onVpn)
      es.addEventListener('mesh_status', onMesh)
      es.addEventListener('auth_status', onAuth)
      es.addEventListener('protection_status', onProtection)
      es.addEventListener('snapshot', onSnap)
      es.addEventListener('heartbeat', onHeartbeat)

      es.onerror = () => {
        if (stopped) return
        clearTimers()
        try { es?.close() } catch { /* ignore */ }
        // Exponential backoff capped at SSE_MAX_BACKOFF_MS.
        reconnectTimer = setTimeout(() => {
          backoffMs = Math.min(backoffMs * 2, SSE_MAX_BACKOFF_MS)
          connect()
        }, backoffMs)
      }

      resetWatchdog()
    }

    connect()

    return () => {
      stopped = true
      clearTimers()
      try { es?.close() } catch { /* ignore */ }
    }
  },

  auth: {
    setTokens: (access_token: string, refresh_token: string, expires_in: number) =>
      post<void>('auth/set-tokens', { access_token, refresh_token, expires_in }),
    logout: () => del<void>('auth/logout'),
    refresh: () => post<void>('auth/refresh'),
  },

  servers: {
    list: () => get<Server[]>('servers'),
  },

  vpn: {
    connect: (server_id: string) => post<void>('vpn/connect', { server_id }),
    disconnect: () => post<void>('vpn/disconnect'),
  },

  mesh: {
    enable: () => post<{ ok: boolean; firewall_warning?: string }>('mesh/enable'),
    disable: () => post<void>('mesh/disable'),
    listExitNodes: () => get<ExitNode[]>('mesh/exit-nodes'),
    setExitNode: (mesh_ip: string, proxy_port: number, proxy_scheme = 'socks5') => post<void>('mesh/exit-node', { mesh_ip, proxy_port, proxy_scheme }),
    clearExitNode: () => del<void>('mesh/exit-node'),
    enableFullTunnel: (mesh_ip: string, proxy_port: number, proxy_scheme = 'socks5') =>
      post<void>('mesh/full-tunnel/enable', { mesh_ip, proxy_port, proxy_scheme }),
    disableFullTunnel: () => post<void>('mesh/full-tunnel/disable'),
  },

  oauth: {
    /** Returns the Authentik authorization URL to open in the system browser. */
    start: () => post<{ url: string }>('oauth/start'),
  },

  settings: {
    get: () => get<UserSettings>('settings'),
    // Backend exposes the same handler under POST /settings so we can use
    // the existing Tauri `agent_post` bridge here.
    put: (s: UserSettings) => post<UserSettings>('settings', s),
  },
}

export interface UserSettings {
  mesh?: { start_disabled?: boolean }
  autostart?: { enabled?: boolean }
}
