//go:build linux

package dns

import (
	"context"
	"fmt"
	"log/slog"
	"net"
	"os"
	"os/exec"
	"strings"
	"sync"
	"time"

	"github.com/goastian/midorivpn-agent/internal/logredact"
)

// resolvconfBackend writes /etc/resolv.conf with the VPN-provided DNS servers
// and tries to make it immutable so NetworkManager / dhclient cannot overwrite
// it. If chattr +i fails (no CAP_LINUX_IMMUTABLE, AppArmor block, or
// /etc unsupported FS) a fallback watcher rewrites the file periodically.
type resolvconfBackend struct {
	mu          sync.Mutex
	applied     bool
	backup      []byte
	content     string
	watchCancel context.CancelFunc
}

func newResolvconfBackend() *resolvconfBackend { return &resolvconfBackend{} }

func (b *resolvconfBackend) Kind() Kind { return KindResolvconf }

func (b *resolvconfBackend) Apply(iface string, servers []string) error {
	_ = iface // unused; kept for interface symmetry

	b.mu.Lock()
	defer b.mu.Unlock()

	slog.Info("dns: protecting via resolvconf", "servers", logredact.IPs(servers))

	if b.backup == nil {
		data, err := os.ReadFile("/etc/resolv.conf")
		if err != nil {
			return fmt.Errorf("backup resolv.conf: %w", err)
		}
		b.backup = append([]byte(nil), data...)
	}

	var sb strings.Builder
	sb.WriteString("# Generated by MidoriVPN while protected mode is active.\n")
	for _, server := range servers {
		server = strings.TrimSpace(server)
		if server == "" {
			continue
		}
		if net.ParseIP(server) == nil {
			return fmt.Errorf("invalid DNS server %q", server)
		}
		sb.WriteString("nameserver ")
		sb.WriteString(server)
		sb.WriteByte('\n')
	}
	content := sb.String()
	slog.Debug("dns: new resolv.conf content", "content", logredact.Generic(content))

	// If NetworkManager manages resolv.conf via a symlink to its own file,
	// write through to the real target first.
	if target, err := os.Readlink("/etc/resolv.conf"); err == nil {
		slog.Info("dns: writing to symlink target", "target", target)
		_ = os.WriteFile(target, []byte(content), 0o644)
	}
	if err := os.WriteFile("/etc/resolv.conf", []byte(content), 0o644); err != nil {
		return fmt.Errorf("write resolv.conf: %w", err)
	}
	slog.Info("dns: wrote resolv.conf successfully")

	// Try to make the file immutable (requires CAP_LINUX_IMMUTABLE).
	// On failure spawn a watcher goroutine that rewrites the file if it
	// gets overwritten by NetworkManager / resolvconf.
	if err := exec.Command("chattr", "+i", "/etc/resolv.conf").Run(); err != nil {
		ctx, cancel := context.WithCancel(context.Background())
		b.watchCancel = cancel
		dnsContent := content
		go func() {
			ticker := time.NewTicker(2 * time.Second)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					cur, err := os.ReadFile("/etc/resolv.conf")
					if err != nil || string(cur) != dnsContent {
						_ = os.WriteFile("/etc/resolv.conf", []byte(dnsContent), 0o644)
					}
				}
			}
		}()
	}

	b.content = content
	b.applied = true
	return nil
}

func (b *resolvconfBackend) Restore() error {
	b.mu.Lock()
	defer b.mu.Unlock()

	if b.watchCancel != nil {
		b.watchCancel()
		b.watchCancel = nil
	}
	if !b.applied {
		return nil
	}
	// Remove the immutable flag (best-effort; only meaningful if chattr +i
	// previously succeeded).
	_ = exec.Command("chattr", "-i", "/etc/resolv.conf").Run()
	if b.backup != nil {
		if err := os.WriteFile("/etc/resolv.conf", b.backup, 0o644); err != nil {
			slog.Warn("dns: failed to restore resolv.conf", "err", err)
		}
	}
	b.applied = false
	b.backup = nil
	b.content = ""
	return nil
}
